rule all:
    input:
        "output.txt",


rule simple_rule:
    input:
        "in{suffix}.txt",
    output:
        "out{suffix}.txt",
    shell:
        "cp {input} {output}"


wildcard_constraints:
    suffix="[put]+",
