rule simple_rule1:
    input:
        "input1.txt",
    output:
        "output1.txt",
    shell:
        "cp {input} {output}"

use rule simple_rule1 as simple_rule2 with:
    input:
        "input2.txt",
    output:
        "output2.txt",

use rule simple_rule2 as simple_rule3 with:
    input:
        "input3.txt",
    output:
        "output3.txt",
