rule all:
    input:
        "aggregated/b.txt",


pass


checkpoint somestep:
    input:
        "samples/{sample}.txt",
    output:
        "somestep/{sample}.txt",
    shell:
        "echo {wildcards.sample} > somestep/{wildcards.sample}.txt"


pass


rule alt_intermediate:
    input:
        "somestep/{sample}.txt",
    output:
        "alt/{sample}.txt",
    shell:
        "touch {output}"


def aggregate_input(wildcards):
    with checkpoints.somestep.get(sample=wildcards.sample).output[0].open() as f:
        if f.read().strip() == "a":
            return "post/{sample}.txt"
        else:
            return "alt/{sample}.txt"
rule aggregate:
    input:
        aggregate_input,
    output:
        "aggregated/{sample}.txt",
    shell:
        "touch {output}"


