rule simple_rule1:
    input:
        "input1.txt",
    output:
        "output1.txt",
    shell:
        "cp {input} {output}"

rule simple_rule2:
    input:
        "input2.txt",
    output:
        "output2.txt",
    shell:
        "cp {input} {output}"
