rule simple_rule1:
    input:
        "input1.txt",
    output:
        "output1.txt",
    shell:
        "cp {input} {output}"


if True:

    rule simple_rule2:
        input:
            "input2.txt",
        output:
            "output2.txt",
        shell:
            "cp {input} {output}"


include_filename = "rules/subfile.smk"


include: include_filename


rule all:
    input:
        "output1.txt",
        "output2.txt",
        "output3.txt",
