rule all:
    input:
        "output1.txt",


rule simple_rule1:
    input:
        "input1.txt",
    output:
        "output1.txt",
    shell:
        "cp {input} {output}"


if True:
    pass


include_filename = "rules/subfile.smk"
include: include_filename
pass


