rule all:
    input:
        "output2.txt",


"""
What a terrible place to have a docstring
"""
pass


rule simple_rule2:
    input:
        "input2.txt",
    output:
        "output2.txt",
    shell:
        "cp {input} {output}"


varname = """ Because this is assigned
to a variable, python should receive
it in the synthetic snakefile
"""
pass


