rule all:
    input:
        "output2.txt",


"""
What a terrible place to have a docstring
"""
pass


rule simple_rule2:
    """ This
    could also be

    one
    """
    input:
        "input2.txt",
    output:
        "output2.txt",
    shell:
        "cp {input} {output}"


""" Maybe

someone put one here
"""
pass


