$schema: "http://json-schema.org/draft-07/schema#"
description: "snakemake_unit_tests user configuration (--config/-c) specification"
type: object
properties:
  output-test-dir:
    type: string
  snakefile:
    type: string
  pipeline-top-dir:
    type: string
  pipeline-run-dir:
    type: string
  inst-dir:
    type: string
  snakemake-log:
    type: string
  added-files:
    type: array
    items:
      type: string
  added-directories:
    type: array
    items:
      type: string
  include-rules:
    type: array
    items:
      type: string
  exclude-rules:
    type: array
    items:
      type: string
  exclude-patterns:
    type: array
    items:
      type: string
  comparators:
    type: array
    items:
      oneOf:
        - type: object
          properties:
            type:
              type: string
              pattern: "^plaintext$|^byte$"
            patterns:
              type: array
              items:
                type: string
          required:
            - type
            - patterns
          additionalProperties: false
        - type: object
          properties:
            type:
              type: string
              pattern: "^frame$"
            patterns:
              type: array
              items:
                type: string
            args:
              type: object
              properties:
                atol:
                  type: number
                rtol:
                  type: number
                header:
                  oneOf:
                    - type: string
                    - type: "null"
                index_col:
                  oneOf:
                    - type: string
                    - type: "null"
                check_like:
                  type: boolean
                sep:
                  type: string
              required:
                - atol
                - rtol
                - header
                - index_col
                - check_like
                - sep
              additionalProperties: false
          additionalProperties: false
additionalProperties: false
