rule all:
    input:
        "output1.txt",
        "output2.txt",
        "output3.txt",


rule simple_rule1:
    input:
        "input1.txt",
    output:
        "output1.txt",
    shell:
        "cp {input} {output}"


include: "level1.smk"
