rule all:
    input:
        "output1.txt",


pass


rule simple_rule1:
    input:
        "input1.txt",
    output:
        "output1.txt",
    shell:
        "cp {input} {output}"


include: "rules/level1.smk"
